version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: course_management_db
    environment:
      POSTGRES_DB: techfrontdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: D9q0vVboLBOPw92uDpgk5lJvTfkbDcVD
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: course_management_app
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DATABASE_URL=Host=dpg-d2emfps9c44c7394sb80-a;Database=techfrontdb;Username=admin;Password=D9q0vVboLBOPw92uDpgk5lJvTfkbDcVD;Port=5432
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: